name: publish to pypi

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: release

    steps:
      - uses: actions/checkout@v4
      - run: pip install build
      - run: python -m build --sdist
      - uses: pypa/gh-action-pypi-publish@release/v1
